services:
    mysql:
        image: mysql:latest
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: test
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - 3306:3306
        volumes:
            - 'mysql_data:/var/lib/mysql'
    redis:
        image: bitnami/redis:latest
        container_name: redis
        restart: always
        environment:
            ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
            - 6379:6379
        volumes:
            - 'redis_data:/bitnami/redis/data'
volumes:
    redis_data:
        driver: local
    mysql_data:
        driver: local